trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: Node install
  inputs:
    versionSpec: '10.x'

- script: 'npm ci'
  displayName: 'npm install'

- script: 'npm run bundle'
  displayName: 'build and bundle'

- script: 'npm run test'
  displayName: 'test'

- script: 'npm run lint'
  displayName: 'lint'

